from enum import Enum


class ErrorType(Enum):
    # Lexer error
    INVALID_EXPONENTIAL_NUMBER = 'LEXICAL-ERROR-INVALID_EXPONENTIAL_NUMBER'
    INVALID_INTEGER_NUMBER = 'LEXICAL-ERROR-INVALID_INTEGER_NUMBER'


class ErrorTypeSemantic(Enum):
    # Semantic error
    TYPE_MISMATCH = 'SEMANTIC-ERROR-TYPE-MISMATCH'
    UNDECLARED_VARIABLE = 'SEMANTIC-ERROR-UNDECLARED-VARIABLE'
    UNDECLARED_FUNCTION = 'SEMANTIC-ERROR-UNDECLARED-FUNCTION'
    USAGE_OF_RESERVED_IDENTIFIER = 'SEMANTIC-ERROR-USAGE-OF-RESERVED-IDENTIFIER'
    MULTIPLE_VARIABLE_DECLARATION = 'SEMANTIC-ERROR-MULTIPLE-VARIABLE-DECLARATION'
    FUNCTION_TYPE_MISMATCH = 'SEMANTIC-ERROR-FUNCTION_TYPE_MISMATCH'
    FUNCTION_PARAMETERS_MISMATCH = 'SEMANTIC-ERROR-FUNCTION_PARAMETERS_MISMATCH'
    EXPRESSION_MULTIPLE_TYPES = 'SEMANTIC-ERROR-EXPRESSION-MULTIPLE-TYPES'
    UNFINISHED_EXPRESSION = 'SEMANTIC-ERROR-UNFINISHED-EXPRESSION'
    MISSING_VARIABLE_NAME = 'SEMANTIC-ERROR-MISSING-VARIABLE-NAME'
    UNKNOWN_DATA_TYPE = 'SEMANTIC-ERROR-UNKNOWN-DATA-TYPE'